# Generated by Django 2.1.7 on 2019-04-16 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('ISBN', models.CharField(db_column='ISBN', max_length=20, primary_key=True, serialize=False, verbose_name='ISBN: ')),
                ('Titulo', models.CharField(db_column='Titulo', max_length=50, verbose_name='Titulo del Libro')),
                ('Autor', models.CharField(db_column='Autor', max_length=50, verbose_name='Autor: ')),
                ('Genero', models.CharField(choices=[('1', 'Accion'), ('2', 'Aventura'), ('3', 'Terror'), ('4', 'Fantasia'), ('5', 'Ciencia Ficcion'), ('6', 'No ficcion/Realidad'), ('7', 'Investigacion'), ('8', 'Biografica'), ('9', 'Infantil'), ('10', 'Autoayuda'), ('11', 'Eroticos/Adultos'), ('12', 'Hogar'), ('13', 'Cocina'), ('14', 'Enciclopedia/Manual'), ('15', 'Politica'), ('16', 'Economia/Marketing'), ('17', 'Socioedad'), ('18', 'Viajes/Cultura'), ('19', 'Historicos'), ('20', 'Clasicos'), ('21', 'Espiritual'), ('22', 'Poesia'), ('23', 'Suspenso'), ('24', 'Otros Temas/ Varios')], db_column='Genero', default='1', max_length=2, verbose_name='Genero: ')),
                ('Editorial', models.CharField(db_column='Editorial', max_length=50, verbose_name='Editorial: ')),
                ('Publicacion', models.DateField(db_column='Publicacion', verbose_name='Fecha de Publicacion: ')),
                ('Edicion', models.CharField(db_column='Edicion', max_length=50, verbose_name='Edicion: ')),
                ('Precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10, verbose_name='Precio: ')),
                ('Portada', models.ImageField(blank=True, db_column='Portada', null=True, upload_to='Portadas', verbose_name='Portada del Libro: ')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('Referencia', models.BigAutoField(db_column='Referencia', primary_key=True, serialize=False, unique=True, verbose_name='Referencia: ')),
                ('Cantidad', models.IntegerField(db_column='Cantidad', default=0, verbose_name='Cantidad: ')),
                ('Total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10, verbose_name='Total: ')),
                ('FechaDePedido', models.DateField(default=datetime.date(2019, 4, 16))),
                ('Nombre', models.CharField(db_column='Cliente', max_length=50, verbose_name='Nombre: ')),
                ('Email', models.EmailField(db_column='Email', max_length=254, verbose_name='Correo Electronico: ')),
                ('Direccion', models.CharField(db_column='Direccion', max_length=100, verbose_name='Direccion: ')),
                ('CP', models.IntegerField(db_column='CP', max_length=5, verbose_name='Codigo Postal')),
                ('Estatus', models.CharField(choices=[('VP', 'Verificando Pago'), ('PV', 'Pago Verificado'), ('PE', 'En Proceso de Envio'), ('E', 'Enviado'), ('R', 'Recibido')], db_column='Estatus', default='VP', max_length=2, verbose_name='Estatus: ')),
                ('ISBN', models.OneToOneField(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='Store.Libros', verbose_name='ISBN')),
            ],
            options={
                'db_table': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(db_column='Cantidad', default=0, verbose_name='Cantidad')),
                ('ISBN', models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='Store.Libros', verbose_name='ISBN: ')),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
    ]
