# Generated by Django 2.1.7 on 2019-04-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='ISBN',
            new_name='ISBN3',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ISBN',
            new_name='ISBN2',
        ),
    ]
