# Generated by Django 2.1.7 on 2019-04-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190416_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ISBN',
            field=models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Store.Libros', verbose_name='ISBN: '),
        ),
    ]
