# Generated by Django 2.1.7 on 2019-04-16 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20190416_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 18, 9, 51, 778058, tzinfo=utc)),
        ),
    ]
