# Generated by Django 2.1.7 on 2019-04-16 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190416_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='CP',
            field=models.IntegerField(db_column='CP', verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 18, 11, 44, 484158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.BigAutoField(db_column='Referencia', primary_key=True, serialize=False, verbose_name='Referencia: '),
        ),
    ]
