# Generated by Django 2.1.7 on 2019-04-16 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20190416_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='Descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Autor',
            field=models.CharField(db_column='Autor', max_length=50, verbose_name='Autor '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Edicion',
            field=models.CharField(db_column='Edicion', max_length=50, verbose_name='Edicion '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Editorial',
            field=models.CharField(db_column='Editorial', max_length=50, verbose_name='Editorial '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='ISBN',
            field=models.CharField(db_column='ISBN', max_length=20, primary_key=True, serialize=False, verbose_name='ISBN '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Portada',
            field=models.ImageField(blank=True, db_column='Portada', null=True, upload_to='Portadas', verbose_name='Portada del Libro '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Precio',
            field=models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10, verbose_name='Precio '),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Publicacion',
            field=models.DateField(db_column='Publicacion', verbose_name='Fecha de Publicacion '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Cantidad',
            field=models.IntegerField(db_column='Cantidad', default=0, verbose_name='Cantidad '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Direccion',
            field=models.CharField(db_column='Direccion', max_length=100, verbose_name='Direccion '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Email',
            field=models.EmailField(db_column='Email', max_length=254, verbose_name='Correo Electronico '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Estatus',
            field=models.CharField(choices=[('VP', 'Verificando Pago'), ('PV', 'Pago Verificado'), ('PE', 'En Proceso de Envio'), ('E', 'Enviado'), ('R', 'Recibido')], db_column='Estatus', default='VP', max_length=2, verbose_name='Estatus '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 19, 33, 0, 663076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Nombre',
            field=models.CharField(db_column='Cliente', max_length=50, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1900043316145454', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia '),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ISBN',
            field=models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Store.Libros', verbose_name='ISBN '),
        ),
    ]
