# Generated by Django 2.1.7 on 2019-04-16 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20190416_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 19, 41, 12, 364402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1912044116146856', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia '),
        ),
    ]
