# Generated by Django 2.1.7 on 2019-04-17 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20190416_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 20, 29, 55, 463238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ISBN',
            field=models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='Store.Libros', verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1955042917153629', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia '),
        ),
    ]
