# Generated by Django 2.1.7 on 2019-04-17 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_auto_20190417_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Cantidad',
            new_name='CantidadInv',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 21, 38, 53, 615583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1953043817161493', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia '),
        ),
    ]
