# Generated by Django 2.1.7 on 2019-04-19 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_auto_20190417_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 17, 2, 2, 986629, tzinfo=utc), verbose_name='Fecha De Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1902040219124361', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia de pago:'),
        ),
    ]
