# Generated by Django 2.1.7 on 2019-04-19 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20190419_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Cantidad',
            field=models.IntegerField(db_column='Cantidad', default=1, verbose_name='Cantidad '),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 17, 20, 18, 303549, tzinfo=utc), verbose_name='Fecha De Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1918042019121739', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia de pago:'),
        ),
    ]
