# Generated by Django 2.1.7 on 2019-04-21 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_auto_20190419_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='Descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', max_length=1000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='FechaDePedido',
            field=models.DateField(default=datetime.datetime(2019, 4, 21, 16, 51, 7, 231350, tzinfo=utc), verbose_name='Fecha De Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Referencia',
            field=models.CharField(db_column='Referencia', default='1907045121115064', max_length=16, primary_key=True, serialize=False, verbose_name='Referencia de pago:'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Telefono',
            field=models.IntegerField(db_column='Telefono', default=0, verbose_name='Telefono'),
        ),
    ]
